name: Build, Test, and Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Run Ruff Check
        run: uv run ruff check .

      - name: Run Tests
        run: uv run pytest

      - name: Build Docker Image
        run: docker build -t churn-prediction-api:latest .

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag churn-prediction-api:latest ${{ secrets.DOCKERHUB_USERNAME }}/churn-prediction-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/churn-prediction-api:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} 
          username: ${{ secrets.EC2_USERNAME }} 
          key: ${{ secrets.EC2_SSH_KEY }}  
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/churn-prediction-api:latest
            docker stop churn-prediction-api || true # In case the container doesn't exist yet
            docker rm churn-prediction-api || true
            docker run -d -p 80:8005 --name churn-prediction-api ${{ secrets.DOCKERHUB_USERNAME }}/churn-prediction-api:latest 

